const C=window.MAGIC_CONFIG;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const services=[['Пультовая охрана','Круглосуточный мониторинг объекта и передача тревоги группе быстрого реагирования.'],['Группы реагирования','Подбор ГБР для выезда на тревожные события с учётом расположения объекта.'],['Охранная сигнализация','Проектирование, оборудование, монтаж и подключение в одной заявке.'],['Видеонаблюдение','Камеры, удалённый доступ и контроль того, что происходит на объекте.'],['AI-видеоаналитика','Обнаружение людей, автомобилей и событий, требующих внимания.'],['Контроль доступа','СКУД, электронные замки, карты и биометрические решения.'],['Физическая охрана','Подбор профессиональной охранной компании под ваш объект и задачу.'],['Монтаж и обслуживание','Установка, настройка и техническое сопровождение оборудования.']];
const steps=[['Пишите нам','Расскажите в чате, какой объект необходимо защитить.'],['Уточняем задачу','Задаём несколько вопросов об объекте и необходимых услугах.'],['Собираем решение','Подбираем охранную компанию, ГБР, оборудование и монтаж.'],['Подключаем охрану','Организуем установку, мониторинг и дальнейшее обслуживание.']];
const cats=[['Квартиры','Сигнализация, тревожная кнопка и реагирование. Контроль дома, даже когда вы далеко.'],['Частные дома','Защита периметра, видеонаблюдение и сигнализация в единой системе.'],['Офисы','Контроль доступа, охрана рабочих пространств и удалённое наблюдение.'],['Магазины','Тревожная кнопка, камеры и охрана торгового зала.'],['Рестораны','Безопасность гостей, сотрудников и служебных помещений.'],['Склады','Контроль периметра, въезда и движения на территории.'],['Производства','Защита территории и контроль доступа на производственные участки.'],['Строительные объекты','Охрана площадки, техники и материалов на каждом этапе работ.'],['Сетевой бизнес','Единый подход к безопасности филиалов в разных городах.'],['Коммерческая недвижимость','Комплексная защита здания, арендаторов и общих зон.']];
const nav=[['services','Услуги'],['how','Как это работает'],['business','Для бизнеса'],['partners','Партнёрам'],['about','О компании'],['reviews','Отзывы'],['contacts','Контакты']];
const page=location.pathname.split('/').pop().replace('.html','')||'index';
const btn=(text='НАПИСАТЬ В ЧАТ')=>`<button class="btn primary" data-chat>${text}<span aria-hidden="true">↗</span></button>`;
function network(){const nodes=[[75,105,'Санкт-Петербург'],[115,200,'Москва'],[175,285,'Казань'],[245,130,'Екатеринбург'],[300,325,'Новосибирск'],[410,135,'Якутск'],[462,290,'Владивосток']];return `<div class="network" aria-label="Схема связей федеральной сети, не карта действующего покрытия"><svg viewBox="0 0 540 420" role="img" aria-label="Единый центр и города России">${nodes.map(([x,y])=>`<line x1="280" y1="210" x2="${x}" y2="${y}"/>`).join('')}<circle class="core" cx="280" cy="210" r="55"/><circle cx="280" cy="210" r="70" fill="none" style="fill:none;stroke:#baff481b"/><text class="core-label" x="280" y="205" text-anchor="middle">MAGIC</text><text class="core-label" x="280" y="225" text-anchor="middle">GUARD</text>${nodes.map(([x,y,n])=>`<g><circle cx="${x}" cy="${y}" r="4"/><circle cx="${x}" cy="${y}" r="11" style="fill:#baff4815"/><text x="${x}" y="${y+25}" text-anchor="middle">${n}</text></g>`).join('')}</svg><div class="network-label">ФЕДЕРАЛЬНАЯ СЕТЬ / КОНЦЕПТУАЛЬНАЯ СХЕМА</div></div>`}
function cards(items,cls=''){return `<div class="cards ${cls}">${items.map(([title,text],i)=>`<article class="card"><span class="num">${String(i+1).padStart(2,'0')} /</span><span class="arrow" aria-hidden="true">↗</span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div>`}
function title(k,h,p=''){return `<div class="section-top"><div><div class="eyebrow">${k}</div><h2>${h}</h2></div>${p?`<p>${p}</p>`:''}</div>`}
function serviceSection(){return `<section><div class="wrap">${title('01 / Экосистема услуг','Всё для безопасности.<br><em>В одном месте.</em>','От первой камеры до комплексной защиты. Соберём решение под вашу задачу.')}${cards(services)}</div></section>`}
function how(){return `<section id="how"><div class="wrap">${title('02 / Просто по делу','Вы пишете.<br>Мы организуем.')}${cards(steps,'steps')}</div></section>`}
function categories(){return `<section><div class="wrap">${title('03 / Ваш объект','Разные задачи.<br><em>Одна точка входа.</em>')}<div class="categories"><div class="category-list" role="tablist" aria-label="Тип объекта">${cats.map(([n],i)=>`<button role="tab" id="tab-${i}" aria-controls="category-panel" aria-selected="${!i}" tabindex="${i?'-1':'0'}" class="${i?'':'active'}" data-cat="${i}">${n}<span aria-hidden="true">↗</span></button>`).join('')}</div><div class="category-detail" id="category-panel" role="tabpanel" aria-labelledby="tab-0"><div class="big-number" aria-hidden="true">01</div><div class="eyebrow">Решение для вашего объекта</div><h3 id="cat-title">${cats[0][0]}</h3><p id="cat-text">${cats[0][1]}</p>${btn('ОБСУДИТЬ ЗАЩИТУ')}</div></div></div></section>`}
function federal(){return `<section><div class="wrap split"><div><div class="eyebrow">04 / Федеральная платформа</div><h2>Одна платформа.<br><em>Вся Россия.</em></h2><p>Объединяем охранные компании, группы быстрого реагирования, монтажные организации и мониторинговую инфраструктуру в единую систему.</p><p>Возможность подключения и состав решения уточняются для вашего адреса.</p><div class="stats">${[['partners','Партнёров'],['cities','Городов'],['objects','Объектов']].map(([k,n])=>`<div class="stat"><strong>${C.stats[k]==null?'—':esc(C.stats[k])}</strong><span>${n}</span></div>`).join('')}</div><p style="font-size:12px">Подтверждённые показатели будут опубликованы после проверки.</p></div>${network()}</div></section>`}
function reviews(){return `<section><div class="wrap">${title('Обратная связь','Нам доверяют<br><em>безопасность.</em>')}<div class="quote-grid">${C.reviews.length?C.reviews.map(r=>`<article class="quote"><div class="badge">${esc(r.city)} / ${esc(r.object)}</div><blockquote>${esc(r.text)}</blockquote><strong>${esc(r.name)}</strong><p>${esc(r.rating)} / 5 · ${esc(r.date)}</p></article>`).join(''):[1,2,3].map(i=>`<article class="quote"><span class="badge">МЕСТО ДЛЯ ОТЗЫВА / ${i}</span><blockquote>Здесь появится реальный опыт наших клиентов.</blockquote><p>Имя / компания · Город · Тип объекта</p><p>Оценка и дата — после публикации</p></article>`).join('')}</div><p style="font-size:13px">Пока отзывы не опубликованы. Карточки выше показывают структуру раздела.</p></div></section>`}
function people(type,heading,roles){const data=C[type].length?C[type]:roles.map(role=>({role}));return `<section><div class="wrap">${title('Команда',heading)}<div class="people">${data.map(p=>`<article class="person"><div class="portrait">${p.photo?`<img src="${esc(p.photo)}" alt="${esc(p.name)}" loading="lazy">`:'Место для реального портрета'}</div><h3>${esc(p.name||'Имя будет опубликовано')}</h3><p>${esc(p.role)}</p>${p.tenure?`<p>В компании: ${esc(p.tenure)}</p>`:''}<p>${esc(p.text||'Информация появится после согласования.')}</p></article>`).join('')}</div></div></section>`}
function cta(){return `<section class="cta"><div class="wrap"><div class="eyebrow" style="justify-content:center">MAGIC GUARD</div><h2>ВАША БЕЗОПАСНОСТЬ<br><em>НАЧИНАЕТСЯ ЗДЕСЬ.</em></h2><p>Опишите задачу. Остальное организует MAGIC GUARD.</p>${btn('ПОДКЛЮЧИТЬ ОХРАНУ')}</div></section>`}
function pageHero(label,h,p){return `<section class="page-hero"><div class="wrap reveal"><div class="eyebrow">${label}</div><h1>${h}</h1><p>${p}</p></div></section>`}
function partnerForm(){return `<section><div class="wrap split"><div><div class="eyebrow">Партнёрская сеть</div><h2>Растите вместе<br>с <em>MAGIC GUARD.</em></h2><p>Приглашаем ЧОП, ГБР и монтажные организации. Расскажите о вашей компании, географии работы и услугах.</p><p class="note">${C.leadEndpoint?'Оставьте заявку на подключение к партнёрской сети.':'Приём заявок ещё не подключён. Форму можно заполнить и скачать как черновик; данные не будут отправлены.'}</p></div><form class="form" id="partner-form"><label>Компания<input name="company" required maxlength="120" autocomplete="organization"></label><label>Город работы<input name="city" required maxlength="100"></label><label>Направление<select name="type"><option>ЧОП</option><option>ГБР</option><option>Монтаж и обслуживание</option></select></label><label>Ваше имя<input name="name" required maxlength="100" autocomplete="name"></label><label>Телефон<input name="phone" required type="tel" autocomplete="tel" placeholder="+7 999 123-45-67"></label><label>О компании<textarea name="details" maxlength="2000"></textarea></label><label class="consent"><input type="checkbox" name="consent" required> <span>Я ознакомлен с <a href="privacy.html">информацией об обработке данных</a> и согласен на обработку заявки.</span></label><button class="btn primary" type="submit">${C.leadEndpoint?'ОТПРАВИТЬ ЗАЯВКУ':'СКАЧАТЬ ЧЕРНОВИК'} ↗</button><div class="status" role="status"></div></form></div></section>`}
let content='';
switch(page){
case 'index': content=`<div class="hero"><div class="wrap"><div class="hero-grid"><div class="hero-copy reveal"><div class="eyebrow">Федеральная платформа безопасности</div><h1>ОХРАНА<br>НАЧИНАЕТСЯ<br><em>С ОДНОГО<br>СООБЩЕНИЯ.</em></h1><p>Подключаем охрану объектов по всей России. Подберём ЧОП, ГБР, оборудование и организуем подключение под ключ.</p><div class="actions">${btn()}<a class="btn" href="#how">КАК ЭТО РАБОТАЕТ <span>↓</span></a></div></div>${network()}</div><div class="hero-foot"><span><strong>Россия</strong> федеральная сеть</span><span><strong>24/7</strong> мониторинг</span><span><strong>Один чат</strong> весь процесс</span></div></div></div><div class="wrap ticker"><span>СИЛА <b> / </b></span><span>ТЕХНОЛОГИИ <b> / </b></span><span>КОНТРОЛЬ <b> / </b></span><span>MAGIC GUARD</span></div>${serviceSection()}${how()}${categories()}${federal()}${reviews()}<section><div class="wrap split"><h2>Растите вместе<br>с <em>MAGIC GUARD.</em></h2><div><p>Подключаем к платформе ЧОП, ГБР и монтажные организации по всей России.</p><a class="btn" href="partners.html">СТАТЬ ПАРТНЁРОМ ↗</a></div></div></section>${cta()}`;break;
case 'services':content=pageHero('Услуги','Охрана.<br><em>Без лишних сложностей.</em>','Вместе определим, что необходимо вашему объекту. Подберём оборудование и исполнителей, организуем подключение.')+serviceSection()+cta();break;
case 'how':content=pageHero('Как это работает','Один чат.<br><em>Четыре шага к защите.</em>','Вам не нужно координировать подрядчиков самостоятельно. MAGIC GUARD собирает процесс в одну понятную последовательность.')+how()+cta();break;
case 'business':content=pageHero('Для бизнеса','Ваш бизнес растёт.<br><em>Защита — вместе с ним.</em>','От одного офиса до сети объектов. Подбираем состав охраны с учётом ваших процессов, географии и требований.')+categories()+federal()+cta();break;
case 'partners':content=pageHero('Партнёрам','Сильнее.<br><em>В единой сети.</em>','Развиваем федеральную инфраструктуру безопасности вместе с профильными организациями.')+partnerForm();break;
case 'about':content=pageHero('О компании','MAGIC GUARD.<br><em>Охрана. Одним сообщением.</em>','Единая точка входа в услуги безопасности. Соединяем клиентов, специалистов и технологии, чтобы сделать подключение охраны понятным.')+federal()+people('leaders','Те, кто стоит<br>за MAGIC GUARD.',['Основатель / CEO','Операционный директор','Технический директор','Руководитель партнёрской сети'])+people('employees','Люди<br><em>MAGIC GUARD.</em>',['Поддержка клиентов','Мониторинг','Техническое направление','Работа с партнёрами']);break;
case 'reviews':content=pageHero('Отзывы','Опыт, который<br><em>имеет значение.</em>','Публикуем отзывы только после подтверждения и согласования с авторами.')+reviews()+people('employees','Люди MAGIC GUARD.',['Поддержка клиентов','Техническое направление']);break;
case 'contacts':content=pageHero('Контакты','Начнём<br><em>с сообщения.</em>','Расскажите, какой объект необходимо защитить и в каком городе он находится.')+`<section><div class="wrap split"><div>${btn()}<p>Чат поможет составить заявку за несколько шагов.</p></div><div>${[['Телефон',C.phone],['Email',C.email],['Адрес',C.address],['Telegram',C.telegram],['VK',C.vk]].map(([k,v])=>`<h3>${k}</h3><p>${v?esc(v):'Будет опубликован после подтверждения'}</p>`).join('')}</div></div></section>`;break;
case 'privacy':case 'terms':case 'consent':content=pageHero('Документы',{'privacy':'Обработка персональных данных','terms':'Пользовательское соглашение','consent':'Согласие на обработку данных'}[page],'Документ готовится к публикации.')+`<section><div class="wrap"><div class="note">Реквизиты оператора и окончательные условия ещё не предоставлены. Приём и передача заявок должны быть включены только после публикации согласованных документов.</div><p>В текущей версии без подключённого сервиса заявки остаются в открытом окне и могут быть скачаны вами. Сайт не сохраняет введённые данные в браузере. Для оформления текста используется Google Fonts, поэтому браузер запрашивает шрифт у внешнего сервиса.</p><p>Для подключения реального приёма заявок необходимо заполнить сведения об операторе, целях и основаниях обработки, сроках хранения и порядке отзыва согласия.</p></div></section>`;break;
default:content=pageHero('404','Страница не найдена','Вернитесь на главную страницу.')+'<div class="wrap"><a class="btn" href="index.html">На главную</a></div>';
}
$('#app').innerHTML=`<a class="skip" href="#main">Перейти к содержимому</a><header><div class="wrap head"><a class="logo" href="index.html" aria-label="MAGIC GUARD — главная"><span class="mark" aria-hidden="true">M</span>MAGIC <small>GUARD</small></a><button class="menu" aria-label="Открыть меню" aria-expanded="false" aria-controls="nav">☰</button><nav id="nav">${nav.map(([p,n])=>`<a href="${p}.html" ${p===page?'aria-current="page"':''}>${n}</a>`).join('')}</nav>${btn('ПОДКЛЮЧИТЬ ОХРАНУ')}</div></header><main id="main">${content}</main><footer class="footer"><div class="wrap"><div class="footer-top"><div><a class="logo" href="index.html">MAGIC <small>GUARD</small></a><p>Федеральная платформа безопасности</p></div><div class="footer-links">${nav.filter(([p])=>p!=='how').map(([p,n])=>`<a href="${p}.html">${n}</a>`).join('')}</div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} MAGIC GUARD</span><a href="privacy.html">Конфиденциальность</a><a href="terms.html">Пользовательское соглашение</a><a href="consent.html">Обработка данных</a><span>Реквизиты готовятся к публикации</span></div></div></footer><button class="chat-launch" data-chat>◉ &nbsp; MAGIC GUARD CHAT &nbsp; ↗</button><dialog class="chat" aria-labelledby="chat-title"><div class="chat-head"><strong id="chat-title">MAGIC GUARD CHAT</strong><button id="close-chat" aria-label="Закрыть чат">×</button></div><div class="chat-body" id="chat-body"></div></dialog>`;
$('.menu').onclick=()=>{const open=$('nav').classList.toggle('open');$('.menu').setAttribute('aria-expanded',String(open))};
function activate(i){document.querySelectorAll('[data-cat]').forEach(b=>{const selected=Number(b.dataset.cat)===i;b.classList.toggle('active',selected);b.setAttribute('aria-selected',selected);b.tabIndex=selected?0:-1});$('#cat-title').textContent=cats[i][0];$('#cat-text').textContent=cats[i][1];$('.big-number').textContent=String(i+1).padStart(2,'0');$('#category-panel').setAttribute('aria-labelledby',`tab-${i}`)}
document.querySelectorAll('[data-cat]').forEach(b=>{b.onclick=()=>activate(Number(b.dataset.cat));b.onmouseenter=()=>{if(matchMedia('(hover:hover)').matches)activate(Number(b.dataset.cat))};b.onkeydown=e=>{if(!['ArrowDown','ArrowUp','Home','End'].includes(e.key))return;e.preventDefault();let i=Number(b.dataset.cat);i=e.key==='Home'?0:e.key==='End'?cats.length-1:(i+(e.key==='ArrowDown'?1:-1)+cats.length)%cats.length;activate(i);$(`[data-cat="${i}"]`).focus()}});
const draft={};let step=0;
function renderChat(){const body=$('#chat-body');if(step===0){body.innerHTML='<div class="bubble">Здравствуйте. Я виртуальный помощник MAGIC GUARD. Какой объект необходимо защитить?</div><div class="chat-choices">'+['Квартира','Дом','Бизнес','Склад','Другой объект'].map(t=>`<button data-type="${t}">${t}</button>`).join('')+'</div><p style="font-size:12px">Помощник собирает заявку по шагам. '+(C.leadEndpoint?'':'Отправка оператору пока недоступна.')+'</p>';body.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{draft.object=b.dataset.type;step=1;renderChat()});return}const questions=['','В каком городе находится объект?','Кратко опишите задачу: площадь, услуги, пожелания.','Как к вам обращаться?','Оставьте телефон для связи.'];if(step<5){body.innerHTML=`<div class="eyebrow">Шаг ${step} / 4</div><div class="bubble">${questions[step]}</div><form id="chat-step"><label>${step===4?'Телефон':'Ваш ответ'}<input name="answer" maxlength="${step===2?1000:100}" required ${step===4?'type="tel" autocomplete="tel"':'type="text"'}></label><button class="btn primary">ДАЛЕЕ →</button><button type="button" id="chat-back" class="btn">НАЗАД</button></form>`;const input=body.querySelector('input');input.value=draft[['','city','details','name','phone'][step]]||'';input.focus();$('#chat-back').onclick=()=>{step--;renderChat()};$('#chat-step').onsubmit=e=>{e.preventDefault();if(!input.value.trim())return;if(step===4&&!validPhone(input.value)){input.setCustomValidity('Укажите телефон: от 10 до 15 цифр.');input.reportValidity();return}draft[['','city','details','name','phone'][step]]=input.value.trim();step++;renderChat()};input.oninput=()=>input.setCustomValidity('');return}body.innerHTML=`<div class="bubble"><strong>Проверьте заявку</strong><br>${['object','city','details','name','phone'].map(k=>esc(draft[k])).join('<br>')}</div><form id="chat-submit"><label class="consent"><input required type="checkbox"><span>Я ознакомлен с <a href="privacy.html">информацией об обработке данных</a> и согласен на обработку заявки.</span></label><button class="btn primary">${C.leadEndpoint?'ОТПРАВИТЬ':'СКАЧАТЬ ЧЕРНОВИК'}</button><button type="button" id="edit-chat" class="btn">ИЗМЕНИТЬ ДАННЫЕ</button><div class="status" role="status">${C.leadEndpoint?'':'Сервис отправки ещё не подключён. Можно сохранить заявку себе; она не поступит оператору.'}</div></form>`;$('#edit-chat').onclick=()=>{step=1;renderChat()};$('#chat-submit').onsubmit=e=>{e.preventDefault();submitLead(e.target,{...draft,source:'chat',consent:true})}}
function validPhone(s){return /^[+\d\s()-]+$/.test(s)&&s.replace(/\D/g,'').length>=10&&s.replace(/\D/g,'').length<=15}
async function submitLead(form,data){const status=form.querySelector('.status'),button=form.querySelector('button[type="submit"]')||form.querySelector('button');if(!validPhone(data.phone)){status.textContent='Проверьте телефон: требуется от 10 до 15 цифр.';return}button.disabled=true;status.textContent='Подготавливаем заявку…';try{if(!C.leadEndpoint){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='magic-guard-request.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Черновик скачан. Оператору заявка не отправлена.'}else{const endpoint=new URL(C.leadEndpoint);if(endpoint.protocol!=='https:')throw Error('Invalid endpoint');const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,consentVersion:'1',submittedAt:new Date().toISOString()}),signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Request failed');status.textContent='Заявка отправлена. Спасибо за обращение!';form.querySelectorAll('input,textarea,select,button').forEach(e=>e.disabled=true)}}catch{status.textContent='Не удалось отправить заявку. Проверьте соединение и попробуйте ещё раз.'}finally{button.disabled=false}}
document.querySelectorAll('[data-chat]').forEach(b=>b.onclick=()=>{$('.chat').showModal();renderChat()});$('#close-chat').onclick=()=>$('.chat').close();
if($('#partner-form'))$('#partner-form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.source='partner';submitLead(e.target,data)};
